### ISSUE TITLE
Sending and receiving a request to backend

### ISSUE THREAD

**Issue by midgetdemon** [CS180-spring/cs180-21-CryPlusPlus#56]
https://github.com/CS180-spring/cs180-21-CryPlusPlus/issues/10
Tests:
#1-Confirm specific collection was created
#2-Confirm collection was deleted
#3-Confirm collection has been accessed
#4-Confirm Document was inserted

**Comment by evarg017-2001** [comment]
Reviewer: Bowen & Eddie
